apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-server-deployment
  namespace: multibranch  # Specify the namespace here
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-server-multi
  template:
    metadata:
      labels:
        app: java-server-multi
    spec:
      containers:
      - name: java-server
        image: romeo23/server-master-jenkins:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: log-volume
          mountPath: /app/logs
        resources:
          requests:
            ephemeral-storage: "500Mi"  # Adjust as needed
          limits:
            ephemeral-storage: "1Gi"  # Adjust as needed
      volumes:
      - name: log-volume
        hostPath:
          path: /var/logs/server # Adjust this path as needed
