apiVersion: v1
kind: Service
metadata:
  name: java-server-service
  namespace: multibranch
spec:
  selector:
    app: java-server-multi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
